### ISSUE TITLE
"Internal server error" when updating Authors on Wagtail

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#107]
When I tried to fill in authors at Wagtail and then clicked "Publish" I got this screen:
![grafik](https://user-images.githubusercontent.com/96528343/173566359-4986e0a0-b47b-459f-babb-c6332f4cb253.png)

Help plz! :)

**Comment by benjaoming** [comment]
I just tested that this works now. I can't point to the specific error here, but I changed a couple of things on the database models of blog posts the past weeks, so it probably got botched there. Should be good to go now :+1:
