### ISSUE TITLE
Blog Categories

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#109]
I have talked with Eberhard and we agreed to keep with the following categories for the blog:

- Campaign
- Book Review
- Monthly Review
- EU Documents
- Extensive Analysis
- Interview
- New Pact
- Opinion
- 
@benjaoming: can I do this myself in wagtail or do we need some of your magic?

**Comment by benjaoming** [comment]
No magic needed, categories can be added/updated/deleted in Wagtail => Snippets

But please wait for the final Blog post import. This can happen as soon as the first Wiki import has taken place and we have mapped out new cross-references between Blog posts and Wiki. I hope soon :)

**Comment by benjaoming** [comment]
An update to the blog categories: They can now be translated. This was missing.

![image](https://user-images.githubusercontent.com/374612/190272325-87538255-5fc2-4222-b66c-293e8e14da23.png)
