### ISSUE TITLE
Blog Editing: Internal server error (1)

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#119]
![image](https://user-images.githubusercontent.com/96528343/178266433-3f140964-427c-4145-a411-def63cb6e0b0.png)

When trying to edit this blog page I get "internal server errer. please fix :)
You find it on page 3 of the listed Blog pages

**Comment by benjaoming** [comment]
@shavek a quick note on these server errors: The error message hides that it's actually often a new type of error. Just wanted to say so you don't think it's the same error that keeps happening :)

I'll get some error handling set up, too!

**Comment by benjaoming** [comment]
The page in question has been fixed.

It appears that some pages may be exported from Wordpress with invalid HTML. I corrected the above manually but I think we can expect more similar errors.

They can be fixed with libtidy.

```
tidy.parseString(html, wrap=0, force_output=True)
```

**Comment by benjaoming** [comment]
This is now generally fixed for all imported HTML. I detected quite a lot of pages with invalid HTML.
