### ISSUE TITLE
Blog Organisation of Content - Include new wagtail filter for sorting blog pages

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#120]
![image](https://user-images.githubusercontent.com/96528343/178267184-233eb6d6-435a-44ec-b7a2-0070e96c24cb.png)

While manually adding all the authors to the blog pages, I noticed a few things that would make the workflow in wagtail a lot better. 

Is it possible to introduce a "date of publication" filter beside the "Updated" "Type" and "Status"?
Another great filter would be: "Published/Unpublished" because it lists both published and unpublished according to time of upload.

If we had these two filter functions it would make editing the Blog section a zillion times easier !

**Comment by benjaoming** [comment]
Yes, it's actually possible! Wow, I missed out on some great stuff here... basically Wagtail can customize these list views A LOT! https://docs.wagtail.org/en/stable/reference/contrib/modeladmin/indexview.html
