### ISSUE TITLE
WIKI: Please create a author field in backend

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#135]
As for the blog we would need a field to fill in authors for the wiki. I could not find it.
thanks :)

**Comment by benjaoming** [comment]
Done :)

**Comment by shavek** [comment]
@benjaoming I just tried to edit the authors in the German Wiki but could not find the author field - maybe its invisible to me?

**Comment by benjaoming** [comment]
This should be okay, just scroll all the way to the very very bottom. I should put the authors in a consistent place, I agree. I'll open up a different issue about tidying up the backend wrt. labels and organizing of fields.
