### ISSUE TITLE
Wiki and Library: Update authors

### ISSUE THREAD

**Issue by benjaoming** [migcontrol/django-migcontrol#145]
The "written by" and "added by" in Wiki and Library are probably wrong since they used the usernames from Wordpress.

They need to be fixed manually.

OR: We can also decide that they shouldn't be there, and I just remove them...

**Comment by shavek** [comment]
@benjaoming 
 Let's delete the "written by" for the WIKI for now. The metadescription field is sufficient and it will save us to work if we do not have to manually add the authors in the wikis in four languages!

So just keep the meta description, delete the "written/added by"!

**Comment by benjaoming** [comment]
This is now done, there is a new "last update" visible on Library and Wiki pages.
