### ISSUE TITLE
Implement Visual Design - Archive

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#16]
![Visual Design_Archiv](https://user-images.githubusercontent.com/96528343/149829539-ea2766cf-621e-4fe6-9f31-443ea54f6e64.jpg)

**Comment by benjaoming** [comment]
Oof, I'm pretty sure that I have somehow never seen this mockup :/

It looks really good, though. I'm gonna have a look at how we can make some progress here.

**Comment by benjaoming** [comment]
This one will be hard to fix quickly since none of the library entries currently have any illustrations.

![image](https://github.com/migcontrol/django-migcontrol/assets/374612/d6e7f9e2-119f-4a1d-91cd-9d04341b2acc)

**Comment by benjaoming** [comment]
The missing "feature image" wasn't available neither in the Wagtail interface. I could add this and then images can be uploaded for the future?

**Comment by shavek** [comment]
I am not sure what this issue is about :) What are WIP Images ?

**Comment by shavek** [comment]
To be honest, I don't think we need any function for images in the library atm, other things are more important

**Comment by shavek** [comment]
I think we skip this for now. We can start thinking about such bigger enhancement at a later stage
