### ISSUE TITLE
Create categories for WIKI

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#160]
I would like to help to create and manually assign the Wiki entries to a couple of categories, like "Europe" or "Agencies". 
If I understood correctly, such things can be done with the Snippets. When I go there, I do see useful categories, but I can't see them in the Wiki or do not know how to apply them there. Once I know, I will get started!

**Comment by benjaoming** [comment]
Roger that! The change will come in with a larger changeset in #158
