### ISSUE TITLE
Implement Visual Design - Wiki Main Page

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#17]
![Visual Design_Wiki](https://user-images.githubusercontent.com/96528343/149829629-6d187265-2c0a-4bbb-8983-4bbc4bdfc6f2.jpg)

**Comment by benjaoming** [comment]
The idea to use geography and maps for the wiki will have to be matured and defined a bit before it is ready to be implemented.

**Comment by shavek** [comment]
yes, lets skip this for now!

**Comment by shavek** [comment]
consider it done :)
