### ISSUE TITLE
Localize wiki category alphabetical order

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#171]
The category snippets for the wiki should be listed in alphabetical order.

In General, all categories we will create for the wiki should always be in alphabetical order

![grafik](https://user-images.githubusercontent.com/96528343/202130863-79bb1960-9458-45a8-92a5-c1a4bea540f8.png)

**Comment by benjaoming** [comment]
Can you explain this one? :)

**Comment by benjaoming** [comment]
Are they not already shown in alphabetical order?

**Comment by shavek** [comment]
You are absolutely right, now that I look again! I guess what confused me was that in German you have the letter "Ä" as in Äthiopien. In the german alphabet it would appear after "A", not at the very end. In English its perfectly fine. Is there a way to chanhge order for "Ä"? If not thats not a big problem, it might be tricky

**Comment by shavek** [comment]
Haha, I even posted a photo of the things in right oder :) I just looked at the end and never looked at the top

**Comment by benjaoming** [comment]
I'll have a look at what sort of issue we could be encountering with the localized ordering. It might be that somehow German isn't active while ordering or that it's ordering the English values instead of the German.

**Comment by shavek** [comment]
It would be fine like this as well! Its a minor issue really

**Comment by benjaoming** [comment]
I looked into this, and I think it's best to accept that it doesn't work all that well for German. It's like the built-in ordering mechanism doesn't do it automatically and there's no way to quickly make it work.

**Comment by shavek** [comment]
Thats alright, thanks for checking it out again

**Comment by benjaoming** [comment]
Found a way to do this :)

**Comment by benjaoming** [comment]
Works now on a couple of places (wiki/media/profiteers) :tada:

![image](https://github.com/migcontrol/django-migcontrol/assets/374612/a692d70b-6a20-4ed6-a5aa-b4f6c65b42be)
