### ISSUE TITLE
Wiki and Material section: Display date of publication, not date of last update

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#187]
We noticed that in the Wiki and Material section, at the top of each entry the date of last update is displayed, but rather we would like the date of publication shown here, which we can edit in the "edit" section of each entry. 

So this is how it looks now: 
![grafik](https://user-images.githubusercontent.com/96528343/232307994-661d3d74-914e-44dd-aa4b-710acb99b801.png)

But we want the date of publication be shown, which we can edit in the backend:
![grafik](https://user-images.githubusercontent.com/96528343/232308021-570265a7-7863-46ff-9219-3490650cd9ff.png)

**Comment by benjaoming** [comment]
This is easy to fix, but would you like this field to be automatically maintained or manual?

**Comment by benjaoming** [comment]
Ah, I misunderstood the original issue: Will make it so there's a clear field that you can manage manually.

Notice that this contradicts having an automatic field. Now you *have* to update it manually.

I'll change the text to say "Published: ..." since that's easier to maintain.
