### ISSUE TITLE
Library #2: Show all Issues / Monthly Review

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#198]
This issue has two dimensions:
1) so far, when you click on "Show all issues" of the Monthly Review in the bottom menu, this leads nowhere. So the first question is where all the monthlys could be collected, apart from the individual entries in the blog. 

Our suggestion would be to direct to the Blog, and more specifically to the Blog category: "All Monthly Reviews". Is it possible to direct not only to the Blog Landing Page, but the Blog Landing Page with the pre-selected category "All Monthly Reviews"?

2) In the Library's sub menue, so far, there is only the Border Business List. We would love it if there was a second item in the menue: "All Monthly Reviews", see in the image attached. 

![Feedback Balder Library 2](https://user-images.githubusercontent.com/96528343/235639481-8da3e7b1-13a3-4a93-bbad-47330932b5f8.png)

**Comment by benjaoming** [comment]
It would be nice if this part can be cleaned up:

![image](https://user-images.githubusercontent.com/374612/235731582-97b9a73d-41e4-44d6-9c14-0c052eb18903.png)

(Blog categories in general, but especially this part)

I think "All entries" and "monthly" should be removed and "All Monthly Reviews" should just be "Monthly Reviews", the "all" part is implicit for all category listings.

**Comment by shavek** [comment]
absolutey agree! Actually, I did this already but it came back after the server switch.

**Comment by shavek** [comment]
> > so far, when you click on "Show all issues" of the Monthly Review in the bottom menu, this leads nowhere. So the first question is where all the monthlys could be collected, apart from the individual entries in the blog.
> 
> This was actually fixed in #196 :)

Was it :) ? If I click here: 
![grafik](https://user-images.githubusercontent.com/96528343/235890495-0875594f-0580-4274-9cae-36b4e804c599.png)
I am directed back to the landing page

**Comment by shavek** [comment]
> It would be nice if this part can be cleaned up:
> 
> ![image](https://user-images.githubusercontent.com/374612/235731582-97b9a73d-41e4-44d6-9c14-0c052eb18903.png)
> 
> (Blog categories in general, but especially this part)
> 
> I think "All entries" and "monthly" should be removed and "All Monthly Reviews" should just be "Monthly Reviews", the "all" part is implicit for all category listings.

done!

**Comment by benjaoming** [comment]
> absolutey agree! Actually, I did this already but it came back after the server switch.

oh shit, sorry! that's definitely not nice, but it's hard with the imports to ensure that they don't overwrite stuff :(

**Comment by benjaoming** [comment]
Oh my, https://github.com/migcontrol/django-migcontrol/pull/196 was never merged :facepalm: But now it is!

**Comment by benjaoming** [comment]
Oh this one is still missing!

> In the Library's sub menue, so far, there is only the Border Business List. We would love it if there was a second item in the menue: "All Monthly Reviews", see in the image attached.
