### ISSUE TITLE
Wiki Landing Page: Info-Text-Field

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#200]
As for the Library and as already implemented on the Blog Landing Page, we would love to have a info-text-field on the right hand side of the Wiki Landing Page, just like for the Blog.

![grafik](https://user-images.githubusercontent.com/96528343/235640880-f40d8bbf-6f90-44c5-9bb2-3e676589f505.png)

**Comment by benjaoming** [comment]
Previously, contents were shown below the page title.

It will look like this now:

![image](https://github.com/migcontrol/django-migcontrol/assets/374612/f66776bb-0e7b-4cb0-876c-cbd06ff4c5b9)

...but you have to add a header (h2) to the body, otherwise it will look strange.
