### ISSUE TITLE
AR Table of Contents not clickable/dynamic

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#202]
We noticed that the table of content in arabic Wiki and Blog entries is not clickable, meaning that you cannot click on a chapter and the text won't move

![grafik](https://user-images.githubusercontent.com/96528343/235642771-a8e558f0-7316-478b-94a3-01d71b2b0d63.png)

EXAMPLES
https://migcontrol.overtag.dk/ar/wiki/egypt

https://migcontrol.overtag.dk/en/blog/d8aad988d986d8b3-d984d98ad8b3d8aa-d8a8d984d8af-d985d986d8b4d8a3-d988d984d8a7-d985d984d8a7d8b0d8a7-d8a2d985d986d8a7-d984d985d986-d98ad8aa/

or https://migcontrol.overtag.dk/en/blog/d8aad8acd8a7d8b1d8a8-d8a7d984d985d987d8a7d8acd8b1d98ad986-d8a7d984d8b3d988d8afd8a7d986d98ad98ad986-d981d98a-d984d98ad8a8d98ad8a7/#header-

**Comment by benjaoming** [comment]
Oh interesting! It turns out that creating a "slug" or simple ASCII letter version automatically from Arabic characters isn't trivial.
