### ISSUE TITLE
Section Cards in the same size?

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#203]
It is possible to fix the size of the section cards to one standard? Perhaps via a limited amount of characters? 200 characters would be good for example. Maybe there are other ways to standardize the size as well :) 

![grafik](https://user-images.githubusercontent.com/96528343/236667470-c391aea8-a6e5-4388-b7f1-5912ceab650d.png)

**Comment by shavek** [comment]
FYI: The Bordner Business List is a new guest on the landing page, since the group wanted it to have more visibility. Fine is working on the dataset. We are still writing a proper description :)

**Comment by benjaoming** [comment]
Fixed!

![image](https://github.com/migcontrol/django-migcontrol/assets/374612/287f86d2-340f-437b-a5bf-3f8d799caf4e)
