### ISSUE TITLE
Highlight Collaborator List Links in Pink

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#205]
Is it possible to higlhight the links in the collaborator list with the light pink that usually links are highlighted with?
![grafik](https://github.com/migcontrol/django-migcontrol/assets/96528343/d3ea37f0-6267-453c-bd5f-af1fe9071c7e)

Like here:
![grafik](https://github.com/migcontrol/django-migcontrol/assets/96528343/ecc628c3-7a73-4da1-bd1d-88ffebd829df)

**Comment by benjaoming** [comment]
Yes, that's easy :)

**Comment by benjaoming** [comment]
Will add soon!
