### ISSUE TITLE
Library: Import of all entries to the same database

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#213]
Hi!

Since our library is only composed of English and German entries, we think its best to treat the whole thing like the blog, meaning that all Libraries draw on the same database and you would arrive there independent from which language setting you're accessing the library.

So if you're on the FR landing page and click on the library, you would see the collection of DE and EN entries. 
The Libraries pages would exist in every language, but have the same database. 

Hope that makes sense!

**Comment by benjaoming** [comment]
For now, I think this makes sense to solve without providing a language filter. I'm not sure what good search filters should be provided, but let me know about this.

It could be for instance:

* Language
* Free text search

I've removed the "media type" filter, it made very little sense IMO.

**Comment by shavek** [comment]
Sounds great!

so you could add these two filters?

- language 
- free text search
