### ISSUE TITLE
Wiki categories:  implement drop down? (no priority)

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#217]
Even though the Wiki category system works super well, there is the issue that country Wikis make up the largest part and thus the list becomes very very long, as you can see when zoomed out: 
![grafik](https://github.com/migcontrol/django-migcontrol/assets/96528343/2dcf24e8-2be4-48a9-890e-a32a636f3865)

We wonder how to make this more user friendly and the main idea and question was whether we could implement a drop down option? 

This has no priority, since it does work, but it would be nice to think of this option.

**Comment by benjaoming** [comment]
I agree, the way that categories pushed down by the long Country listing doesn't work well. Making all categories equally long with a collapsible option would work better. Or maybe that each category has the same height and has its own little scrolling view.

**Comment by shavek** [comment]
Both sound like good ideas, so I can't visualize it well to myself. What would be the easier thing to implement on your side?

**Comment by benjaoming** [comment]
Both options are equally easy to create, but I think for the user, the _scrolling_ solution will be nicer.

Hiding/showing contents will create the situation where there might be several de-collapsed boxes of unequal height, which will probably look similar to the current the layout issue that we have.

**Comment by shavek** [comment]
Yes, that make sense. Please go ahead with the scrolling option, if you know how to implement this !
