### ISSUE TITLE
Logo: New vector graphics

### ISSUE THREAD

**Issue by benjaoming** [migcontrol/django-migcontrol#223]
I believe that we had a TODO about adding a version of the logo that's more clearly drawn, for instance as a vector (SVG) graphic.

**Comment by shavek** [comment]
Yes We have a new logo. We realized that we're being misunderstood as being pro migration-control sometimes, so we have made a new logo crossing out the "control". I will send this to you asap as vector graphic, just asked the crew to provide it to me

**Comment by benjaoming** [comment]
@shavek I understand the concern! have added the new logo as-is.
