### ISSUE TITLE
Fix link in "Subscribe" section + form is missing

### ISSUE THREAD

**Issue by benjaoming** [migcontrol/django-migcontrol#233]
Link should point here: https://new.migration-control.info/en/blog/category/monthly_review/

Maybe it's better to just write "Subscribe at the bottom of this page" or similar?

![image](https://github.com/migcontrol/django-migcontrol/assets/374612/0f6d4972-bf76-48b6-91f5-c4d6d2008e05)

**Comment by shavek** [comment]
good idea, will do that now

**Comment by benjaoming** [comment]
seems done :+1:
