### ISSUE TITLE
Library Pages

### ISSUE THREAD

**Issue by ebju** [migcontrol/django-migcontrol#256]
On the library child pages, we have "author" in the backend, but it is not schown in the front end.
Since some persons want to add academic articles, it would be good if authors also shown in the front end.

**Comment by benjaoming** [comment]
Great idea! @teabag12 this is an easy change, so I just wonder if you would like to do it and ask for help? :)

**Comment by teabag12** [comment]
For clarification, e.g. in this [example](https://migration-control.info/en/library/governance-and-security-in-the-sahel-tackling-mobility-demography-and-climate-change/), the author of the media's description should be credited somewhere, correct? 

![Screenshot from 2024-01-29 16-51-41](https://github.com/migcontrol/django-migcontrol/assets/89033537/c8ff977d-7a76-4ab8-a67e-c03c6c927bf3)

Maybe not in the table together with the media's metadata, though, but instead in parenthesis at the end of the description, I would suggest?

**Comment by benjaoming** [comment]
I think it belongs in the table below or above "Publisher".

**Comment by ebju** [comment]
Dear,

when we post a scientific article, the name of authors (not of the one
who posted it, but authors of the posted medium) shoulb be seen in the
table, between "Full title" and "Publisher".

Best greetings, Eb

Am 29.01.2024 um 16:57 schrieb teabag12:

**Comment by benjaoming** [comment]
It's been fixed now @ebju :tada:

**Comment by ebju** [comment]
Thank you so much!
All the Best, Eb


Am 01.02.2024 um 14:03 schrieb Benjamin Balder Bach:
