### ISSUE TITLE
wrong link in the "Border Profiteers List" black box on landing page

### ISSUE THREAD

**Issue by hansixyz** [migcontrol/django-migcontrol#259]
it is me again, Hanne, and I have the same problem, but with another black box on the landing page and another page that i can not find to interlink and solve the problem myself ;)

The "Read more" in the Border Profiteers List black box on the English landing page leads to the German border profiteers list, not the English one. If I am on the German border business lsit and click "EN" in the language selection, I can access the English border profiteers list (https://migration-control.info/en/library/profiteers/). I am failing to find the Border business list in the list of possible sites to link to, so I can't fix the problem myself. please help me, I would like to understand how to do this myself.

@balder, fine also wanted to reach out, so you are maybe already aware of :)

**Comment by benjaoming** [comment]
Hi :wave: 

This is fixed now :+1: 

You can fix most such things by finding the correct element in Wagtail. For instance, this one is controlled by an element that displays text and has a chosen page to link to:

![image](https://github.com/migcontrol/django-migcontrol/assets/374612/88e82dd6-d9c6-4225-b7a8-7159189d5709)
