### ISSUE TITLE
Change "SOCIAL LINKS" to "SOCIAL MEDIA"

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#26]
![Bildschirmfoto vom 2022-01-17 20-57-28](https://user-images.githubusercontent.com/96528343/149831815-6ecc2f79-f385-4d21-add4-9238add8b372.png)

Please change "SOCIAL LINKS" to "SOCIAL MEDIA"

_Originally posted by @shavek in https://github.com/migcontrol/django-migcontrol/issues/15#issuecomment-1014859103_

**Comment by benjaoming** [comment]
Fixed in #48 by @tchiliali :)
