### ISSUE TITLE
Example HTML content and styling for landing page "info boxes" (About/Blog/Wiki)

### ISSUE THREAD

**Issue by benjaoming** [migcontrol/django-migcontrol#58]
Related to #15

**Comment by benjaoming** [comment]
Some links from the conversation 2 weeks ago:

The 3 columns should be implemented using the Wagtail grid system as 3 columns.

* https://getbootstrap.com/docs/5.1/layout/grid/
* https://getbootstrap.com/docs/5.1/layout/breakpoints/

It's possible to lay out the 3 boxes using the card element. Further reading about this: https://getbootstrap.com/docs/5.1/components/card/ (this was how the Blog index page was set up)

The file to do example HTML in: https://github.com/migcontrol/django-migcontrol/blob/main/home/templates/home/home_page.html

There's also a nice Wagtail tutorial here, we will expand the example HTML to use data directly from Wagtail afterwards: https://docs.wagtail.org/en/stable/getting_started/tutorial.html

**Comment by tchiliali** [comment]
#15
This is progress
