### ISSUE TITLE
BLOG: Add description Text at the right side

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#74]
On the old page we have a little description about the content of the blog at the top, see here:
![grafik](https://user-images.githubusercontent.com/96528343/167390498-ece19b24-de37-45c5-b115-95a6b1b0a7d2.png)

On the new site we have this useful blank space on the right hand site. Would it be possible to add a text section there for the description?

Here: 
![grafik](https://user-images.githubusercontent.com/96528343/167390698-d13fb62b-d701-40b0-b81d-9a13be3e52e0.png)

We have this description text in all the four languages. I will add them here:

ENGLISH:
News, comments and reports that are important in relation to our questions. The blog is multilingual. Individual contributions are highlighted as Extensive Analysis Post. The [Monthly Review](https://migration-control.info/monthly-review-list/), a monthly compilation of interesting articles and reports, has been available since October 2020.

GERMAN:
Nachrichten, Kommentare und Berichte, die in Bezug auf unsere Fragen wichtig sind. Der Blog ist mehrsprachig. Einzelne Beiträge sind als Extensive Analysis Post hervorgehoben. Seit Oktober 2020 gibt die [Monthly Review](https://migration-control.info/monthly-review-list/), eine monatliche Zusammenstellung interessanter Artikel und Reports.

FRENCH:
Des nouvelles, des commentaires et des rapports qui sont importants par rapport à nos questions. Le blog est multilingue. Quelques messages individuels sont mis en évidence comme Extensive Analysis Post. Depuis octobre 2020, [Monthly Review](https://migration-control.info/monthly-review-list/), une compilation mensuelle d’articles et de rapports intéressants.

**Comment by benjaoming** [comment]
That's a really good idea and not hard to do!
