### ISSUE TITLE
Blog: Error importing footnoes

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#76]
Just saw that there is a problem with the import of footnotes.

Here is how it looks on wordpress:
![image](https://user-images.githubusercontent.com/96528343/168760885-4b5c991e-14dc-400d-867e-3b0783ef6218.png)

Here is how it looks on our new page: 
![image](https://user-images.githubusercontent.com/96528343/168761060-638d26ac-ab10-4153-b11f-f20de0609bfe.png)

Wondering if there is a quick fix or if thats a manual talks to go through all of them (hope not!)

**Comment by benjaoming** [comment]
This is fixed now. If you see any blog posts that do not have correct footnotes, it might be that they are old imports that should be deleted (I found 1, but haven't seen more).

**Comment by benjaoming** [comment]
Here is the blog post in question, now with correctly imported footnotes: https://migcontrol.overtag.dk/en/blog/new-eu-document-operationalization-of-the-pact-migratory-relations-with-serbia/
