### ISSUE TITLE
Blog: Filter function

### ISSUE THREAD

**Issue by shavek** [migcontrol/django-migcontrol#77]
On the old page we have a filter function:

![image](https://user-images.githubusercontent.com/96528343/168766080-a5ad90eb-0a00-40d2-b31c-e3c994d8ede3.png)

Can we implement something like this on our new blog too? I will have to ask back to the team about the categories we need, but certainly it will be:

Language Filter: EN, AR, DE, FR
Monthly Review
Internal EU Documents
Analysis
Campaign
Book Review
All Entries

**Comment by benjaoming** [comment]
Languages will be one type of choices
Categories will be created for the following: Monthly Review, Internal EU Documents, Analysis, Campaign, Book Review

Categories should be translateable and sensitive to the active translation.
