### ISSUE TITLE
Blog structure and import

### ISSUE THREAD

**Issue by benjaoming** [migcontrol/django-migcontrol#9]

**Comment by LiloliloJejo** [comment]
Conclusion: Migration control regarding blog languages - all languages on display and filter function similar to the one which is currently available, but the description text (what is the blog) should change in par with the language selection

**Comment by shavek** [comment]
![grafik](https://user-images.githubusercontent.com/96528343/151207873-505a42f0-7b3e-42b1-ba34-e9000766ab2e.png)

We need the option to align images either on the left, the center or the right side of the post.

Also we need the option for the text to be displayed beside the images, see example from old site beneath.

![grafik](https://user-images.githubusercontent.com/96528343/151207955-3205e988-4511-436b-8bd7-cbc6340867b5.png)

**Comment by LiloliloJejo** [comment]
![grafik](https://user-images.githubusercontent.com/96542967/151209138-2c46c5f8-4063-40cd-b6a4-3653b0de04e9.png)

**Comment by shavek** [comment]
![grafik](https://user-images.githubusercontent.com/96528343/151208042-f2ceba53-8360-48f6-a64c-059564f16913.png)

![grafik](https://user-images.githubusercontent.com/96528343/151208079-0a99f760-b040-4023-8027-17934898dc39.png)

Above many of the pictures there is this line of text, which needs to be removed. It does not always happen, but more than 50 per cent of the time.

**Comment by LiloliloJejo** [comment]
would it be possible to add distance between the date and main text, as in old website: 

![grafik](https://user-images.githubusercontent.com/96542967/151209379-06cdf500-7240-4886-b354-5714899ecf93.png)

>>> distance


![grafik](https://user-images.githubusercontent.com/96542967/151209443-10920a8d-4506-468c-aaa2-41b49440d88a.png)

>>> no distance (color, also see Wasli)

**Comment by shavek** [comment]
![grafik](https://user-images.githubusercontent.com/96528343/151209472-766e4f89-0f51-4fad-af86-ae5730fe8bc0.png)

The date of publication should be displayed more prominently, like on the old website (foto beneath). It does not have to be clickable, just set apart by colour in pink.

![grafik](https://user-images.githubusercontent.com/96528343/151209563-18c6c19c-9361-4f39-985d-db70b4a32472.png)

**Comment by LiloliloJejo** [comment]
would it also be possible to add a distance between date and text, see old new comparison: 

old: 
![grafik](https://user-images.githubusercontent.com/96542967/151209654-9d1ed821-453b-4e84-b6ec-c970fe235af5.png)
 

new: 
![grafik](https://user-images.githubusercontent.com/96542967/151209754-6052d095-ca21-4d6b-9e76-4a6d2b14804e.png)

**Comment by LiloliloJejo** [comment]
would it be possible to have the text centrally aligned, as in previous blog (see above?)

**Comment by LiloliloJejo** [comment]
table of content is missing in some blog posts: 

old version: 
![grafik](https://user-images.githubusercontent.com/96542967/151210727-52c19381-a18d-42d1-a3ec-242b7be905c5.png)

new version: 
![grafik](https://user-images.githubusercontent.com/96542967/151210825-fa84e42b-4870-48a0-b20c-047f57639a7c.png)

**Comment by LiloliloJejo** [comment]
is there a possibility to include title pictures in blog posts, similar to wordpress format: 

old: 
![grafik](https://user-images.githubusercontent.com/96542967/151211123-3ed1bf65-b567-438e-bd77-65c07a5a68f3.png)


new: 
![grafik](https://user-images.githubusercontent.com/96542967/151211067-7693cdc4-719d-495f-bed7-c22aa84d8fb2.png)

**Comment by shavek** [comment]
![grafik](https://user-images.githubusercontent.com/96528343/151211214-882e77d5-c305-4323-975b-374114dfbd11.png)

Remove that small text bit after the description of image. This text bit appears in many other blog posts too

**Comment by LiloliloJejo** [comment]
would it be possible to have the citations a little bit more inward, like in the original blog posts? 

new: 
![grafik](https://user-images.githubusercontent.com/96542967/151211692-b16b0120-5df0-4fa8-9992-b61a5edb275e.png)

old: 
![grafik](https://user-images.githubusercontent.com/96542967/151211876-2a60fdba-e673-4fe3-91c9-1a87d0aa4505.png)

**Comment by benjaoming** [comment]
Closing this - remaining issues surrounding captions and footnotes have separate issues open.
